# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gym1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 546)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setContentsMargins(-1, 3, -1, 5)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, 11, -1)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(Form)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_9.addWidget(self.line_3)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.modname = QtWidgets.QLineEdit(Form)
        self.modname.setObjectName("modname")
        self.horizontalLayout_9.addWidget(self.modname)
        self.horizontalLayout_9.setStretch(3, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 10, -1)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.outputpath = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputpath.sizePolicy().hasHeightForWidth())
        self.outputpath.setSizePolicy(sizePolicy)
        self.outputpath.setToolTip("")
        self.outputpath.setObjectName("outputpath")
        self.horizontalLayout.addWidget(self.outputpath)
        self.open_output = QtWidgets.QToolButton(Form)
        self.open_output.setObjectName("open_output")
        self.horizontalLayout.addWidget(self.open_output)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setContentsMargins(-1, 2, -1, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.traindatapath = QtWidgets.QLineEdit(self.groupBox)
        self.traindatapath.setObjectName("traindatapath")
        self.horizontalLayout_2.addWidget(self.traindatapath)
        self.but_traindatapath = QtWidgets.QToolButton(self.groupBox)
        self.but_traindatapath.setObjectName("but_traindatapath")
        self.horizontalLayout_2.addWidget(self.but_traindatapath)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.eval_ck = QtWidgets.QCheckBox(self.groupBox)
        self.eval_ck.setMinimumSize(QtCore.QSize(100, 20))
        self.eval_ck.setMaximumSize(QtCore.QSize(140, 16777215))
        self.eval_ck.setObjectName("eval_ck")
        self.horizontalLayout_3.addWidget(self.eval_ck)
        self.eval_entry = QtWidgets.QLineEdit(self.groupBox)
        self.eval_entry.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eval_entry.sizePolicy().hasHeightForWidth())
        self.eval_entry.setSizePolicy(sizePolicy)
        self.eval_entry.setMaximumSize(QtCore.QSize(30, 16777215))
        self.eval_entry.setInputMethodHints(QtCore.Qt.ImhNone)
        self.eval_entry.setInputMask("")
        self.eval_entry.setDragEnabled(False)
        self.eval_entry.setObjectName("eval_entry")
        self.horizontalLayout_3.addWidget(self.eval_entry)
        spacerItem = QtWidgets.QSpacerItem(43, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(-1, 4, -1, 4)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.model_rb1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.model_rb1.setObjectName("model_rb1")
        self.horizontalLayout_4.addWidget(self.model_rb1)
        self.existmodelpath = QtWidgets.QLineEdit(self.groupBox_2)
        self.existmodelpath.setEnabled(False)
        self.existmodelpath.setObjectName("existmodelpath")
        self.horizontalLayout_4.addWidget(self.existmodelpath)
        self.but_existmodelpath = QtWidgets.QToolButton(self.groupBox_2)
        self.but_existmodelpath.setEnabled(False)
        self.but_existmodelpath.setObjectName("but_existmodelpath")
        self.horizontalLayout_4.addWidget(self.but_existmodelpath)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.model_rb2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.model_rb2.setChecked(True)
        self.model_rb2.setObjectName("model_rb2")
        self.horizontalLayout_5.addWidget(self.model_rb2)
        self.lang_combo = QtWidgets.QComboBox(self.groupBox_2)
        self.lang_combo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lang_combo.setObjectName("lang_combo")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.lang_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.lang_combo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setContentsMargins(-1, 2, -1, 4)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.iter_entry = QtWidgets.QLineEdit(self.groupBox_3)
        self.iter_entry.setMinimumSize(QtCore.QSize(45, 0))
        self.iter_entry.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.iter_entry.setFont(font)
        self.iter_entry.setInputMethodHints(QtCore.Qt.ImhNone)
        self.iter_entry.setInputMask("")
        self.iter_entry.setText("")
        self.iter_entry.setObjectName("iter_entry")
        self.gridLayout_2.addWidget(self.iter_entry, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lr_entry = QtWidgets.QLineEdit(self.groupBox_3)
        self.lr_entry.setMinimumSize(QtCore.QSize(45, 0))
        self.lr_entry.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.lr_entry.setFont(font)
        self.lr_entry.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lr_entry.setInputMask("")
        self.lr_entry.setText("")
        self.lr_entry.setObjectName("lr_entry")
        self.gridLayout_2.addWidget(self.lr_entry, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.drop_entry = QtWidgets.QLineEdit(self.groupBox_3)
        self.drop_entry.setMinimumSize(QtCore.QSize(45, 0))
        self.drop_entry.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.drop_entry.setFont(font)
        self.drop_entry.setObjectName("drop_entry")
        self.gridLayout_2.addWidget(self.drop_entry, 2, 1, 1, 1)
        self.averaging = QtWidgets.QCheckBox(self.groupBox_3)
        self.averaging.setObjectName("averaging")
        self.gridLayout_2.addWidget(self.averaging, 3, 0, 1, 2)
        self.horizontalLayout_7.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setMaximumSize(QtCore.QSize(16777215, 100))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tagger = QtWidgets.QCheckBox(self.groupBox_3)
        self.Tagger.setChecked(True)
        self.Tagger.setObjectName("Tagger")
        self.verticalLayout.addWidget(self.Tagger)
        self.Parser = QtWidgets.QCheckBox(self.groupBox_3)
        self.Parser.setChecked(True)
        self.Parser.setObjectName("Parser")
        self.verticalLayout.addWidget(self.Parser)
        self.Ner = QtWidgets.QCheckBox(self.groupBox_3)
        self.Ner.setChecked(True)
        self.Ner.setObjectName("Ner")
        self.verticalLayout.addWidget(self.Ner)
        self.Cat = QtWidgets.QCheckBox(self.groupBox_3)
        self.Cat.setChecked(True)
        self.Cat.setObjectName("Cat")
        self.verticalLayout.addWidget(self.Cat)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.mbatch = QtWidgets.QCheckBox(self.groupBox_3)
        self.mbatch.setChecked(True)
        self.mbatch.setObjectName("mbatch")
        self.verticalLayout_2.addWidget(self.mbatch)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.frame = QtWidgets.QFrame(self.groupBox_3)
        self.frame.setMaximumSize(QtCore.QSize(164, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.comp_fac = QtWidgets.QLineEdit(self.frame)
        self.comp_fac.setObjectName("comp_fac")
        self.gridLayout.addWidget(self.comp_fac, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.comp_stop = QtWidgets.QLineEdit(self.frame)
        self.comp_stop.setObjectName("comp_stop")
        self.gridLayout.addWidget(self.comp_stop, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.comp_start = QtWidgets.QLineEdit(self.frame)
        self.comp_start.setObjectName("comp_start")
        self.gridLayout.addWidget(self.comp_start, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(94, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_7.setStretch(5, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(22, 21))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.textfield = QtWidgets.QTextEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.textfield.setFont(font)
        self.textfield.setStyleSheet("QTextEdit {background-color: \'#222222\';\n"
"color:\'#EEEEEE\'; selection-background-color:\"#6b6b6b\"}")
        self.textfield.setObjectName("textfield")
        self.verticalLayout_5.addWidget(self.textfield)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_8.addWidget(self.progressBar)
        self.start_but = QtWidgets.QPushButton(Form)
        self.start_but.setMaximumSize(QtCore.QSize(45, 16777215))
        self.start_but.setStyleSheet("background-color: rgb(102, 255, 94);")
        self.start_but.setObjectName("start_but")
        self.horizontalLayout_8.addWidget(self.start_but)
        self.disrupt_save_but = QtWidgets.QPushButton(Form)
        self.disrupt_save_but.setStyleSheet("background-color: rgb(102, 197, 255);")
        self.disrupt_save_but.setObjectName("disrupt_save_but")
        self.horizontalLayout_8.addWidget(self.disrupt_save_but)
        self.disrupt_but = QtWidgets.QPushButton(Form)
        self.disrupt_but.setMaximumSize(QtCore.QSize(45, 16777215))
        self.disrupt_but.setStyleSheet("background-color: rgb(255, 97, 131);")
        self.disrupt_but.setObjectName("disrupt_but")
        self.horizontalLayout_8.addWidget(self.disrupt_but)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.setStretch(6, 1)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.eval_ck.toggled['bool'].connect(self.eval_entry.setEnabled)
        self.model_rb2.toggled['bool'].connect(self.lang_combo.setEnabled)
        self.model_rb1.toggled['bool'].connect(self.existmodelpath.setEnabled)
        self.model_rb1.toggled['bool'].connect(self.but_existmodelpath.setEnabled)
        self.mbatch.toggled['bool'].connect(self.comp_start.setEnabled)
        self.mbatch.toggled['bool'].connect(self.comp_stop.setEnabled)
        self.mbatch.toggled['bool'].connect(self.comp_fac.setEnabled)
        self.pushButton_2.clicked.connect(self.textfield.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Neural Gym"))
        self.label.setText(_translate("Form", "Create an output directory for saving new model"))
        self.label_12.setText(_translate("Form", "Model name:"))
        self.modname.setToolTip(_translate("Form", "Name will be saved to model meta file"))
        self.label_2.setText(_translate("Form", "Output directory:"))
        self.open_output.setText(_translate("Form", "..."))
        self.groupBox.setTitle(_translate("Form", "Training DATA"))
        self.label_3.setText(_translate("Form", "Training DATA file:"))
        self.but_traindatapath.setText(_translate("Form", "..."))
        self.eval_ck.setText(_translate("Form", "Split evaluation DATA %"))
        self.eval_entry.setToolTip(_translate("Form", "Number between 0 and 1 (Default value  = 0.2)"))
        self.eval_entry.setText(_translate("Form", "0.2"))
        self.groupBox_2.setTitle(_translate("Form", "Select model to train"))
        self.model_rb1.setToolTip(_translate("Form", "Load model from path"))
        self.model_rb1.setText(_translate("Form", "Load model:"))
        self.but_existmodelpath.setText(_translate("Form", "..."))
        self.model_rb2.setToolTip(_translate("Form", "create a blank model"))
        self.model_rb2.setText(_translate("Form", "Blank model"))
        self.lang_combo.setItemText(0, _translate("Form", "en"))
        self.lang_combo.setItemText(1, _translate("Form", "es"))
        self.lang_combo.setItemText(2, _translate("Form", "de"))
        self.lang_combo.setItemText(3, _translate("Form", "pt"))
        self.lang_combo.setItemText(4, _translate("Form", "fr"))
        self.lang_combo.setItemText(5, _translate("Form", "it"))
        self.lang_combo.setItemText(6, _translate("Form", "nl"))
        self.lang_combo.setItemText(7, _translate("Form", "xx"))
        self.groupBox_3.setTitle(_translate("Form", "Training options"))
        self.label_4.setText(_translate("Form", "Number of iterations:"))
        self.iter_entry.setToolTip(_translate("Form", "Any integer number"))
        self.label_5.setText(_translate("Form", "Learning rate:"))
        self.lr_entry.setToolTip(_translate("Form", "Number between 0 and 1 (Default value  = 0.001)"))
        self.label_6.setText(_translate("Form", "Dropout rate(0...1):"))
        self.drop_entry.setToolTip(_translate("Form", "Number between 0 and 1 (Default value  = 0.2)"))
        self.averaging.setText(_translate("Form", "Parameter averaging"))
        self.Tagger.setText(_translate("Form", "Train tagger"))
        self.Parser.setText(_translate("Form", "Train parser"))
        self.Ner.setText(_translate("Form", "Train NER"))
        self.Cat.setText(_translate("Form", "Train textcat"))
        self.mbatch.setText(_translate("Form", "Minibatch"))
        self.label_7.setText(_translate("Form", "Compounding:"))
        self.label_9.setText(_translate("Form", "Stop"))
        self.label_8.setText(_translate("Form", "Start"))
        self.label_10.setText(_translate("Form", "Factor"))
        self.label_11.setText(_translate("Form", "Training..."))
        self.pushButton_2.setToolTip(_translate("Form", "clear output window"))
        self.pushButton_2.setText(_translate("Form", "❎"))
        self.pushButton.setText(_translate("Form", "Close"))
        self.start_but.setText(_translate("Form", "Start"))
        self.disrupt_save_but.setText(_translate("Form", "Stop and Save"))
        self.disrupt_but.setText(_translate("Form", "Stop"))

